### ISSUE TITLE
[BUG] (U9CGgTmPULR32-Robin_mini (QQSP) missing Special_menuDelta)

### ISSUE THREAD

**Issue by peeepeeepeee** [Foxies-CSTL/Marlin_2.1.x#16]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Special Delta menu is missing on U9CGgTmPULR32-Robin_mini (QQSP)
Just Flashed the mentioned version of Foxies Firmware, and cant get any Delta Leveling to work
I hope I'm posting this in the right section... sorry if not...
![IMG_20230129_194247](https://user-images.githubusercontent.com/13998756/215348914-a958432b-7dd3-45c4-8748-7ebe50577f98.jpg)
![IMG_20230129_194240](https://user-images.githubusercontent.com/13998756/215348915-971c8530-15f5-48da-835a-66ced6619377.jpg)

### Version of Marlin Firmware

Marlin FLSunQ_2.1.1

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by Foxies-CSTL** [comment]
> U9CGgTmPULR32

This firmware implies that you have wired the TMC2209 in UART mode (4 wires) (option 'U9'), that you have modified the jumper under the stepper motor drivers and that you have also wired the DIAG pin of the TMC to the Signal pin of each EndStop (SENSORLESS: Homing/Probing: Option "g" and "G") .
The STALLGUARD_2 function of the TMCs disables the "Special Delta" menu but all settings are available in the "advanced configuration" menu.
