### ISSUE TITLE
[BUG] Nothing happends after Updateing 100%

### ISSUE THREAD

**Issue by Xcat2008** [Foxies-CSTL/Marlin_2.1.x#17]
### Did you test the latest `bugfix-2.1.x` code?

No, but I will test it now!

### Bug Description

I have downloaded this Firmware ( QQS_TS35-U9CBPULR32_Robin_nano_v3.bin ) and start erasing sectors and then updating.. when get 100% bips, so i'm supposed to take out the sd card, or usb drive (tested both) and start the printer again? Only black screen. I have one kit that ive purchased maybe 1 year ago or 2, MKS Robin nano V3.1 + MKS TS35. I'm sorry, need help to make Marlin work on my delta qqs pro.

### Version of Marlin Firmware

#000000

### Printer model

FLsun QQS Pro

### Electronics

MKS Robin Nano V3.1 + BGM Extruder

### Bed Leveling

None

### Your Slicer

Cura

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by Foxies-CSTL** [comment]
Hi, 
Try it with the latest version for MoBo SKR/MKS: Asset Pack or the "Firmwares" branch.
