### ISSUE TITLE
Add support for the original wifi firmware

### ISSUE THREAD

**Issue by Milkman337** [Foxies-CSTL/Marlin_2.1.x#2]
### Is your feature request related to a problem? Please describe.

I cant get the esp32 new wifi firmware to run

### Describe the feature you want

Please make marlin compatible with the qqs pro stock wifi firmware

**Comment by Foxies-CSTL** [comment]
The firmware of the Wifi module is available on this page of my Wifi. 
https://github.com/Foxies-CSTL/Marlin_2.1.x/wiki/5.Firmware-Wifi
To talk with Marlin, you need to enable an additional communication channel (#define SERIAL_PORT_2 1 for the QQS/Q5 printer) in the Marlin source or use a binary with the "W" option.

**Comment by Milkman337** [comment]
but the wifi firmware from here(https://github.com/Foxies-CSTL/Marlin_2.1.x/wiki/5.Firmware-Wifi) doesnt work it says some error it says wrong data and sometimes it doesnt even work it flashes yes but nothing happens after no ap 

also note that the qqs pro has an esp12s in it

**Comment by Foxies-CSTL** [comment]
> also note that the qqs pro has an esp12s in it

Yes, I know that and the stock Wifi firmware only works with the MKS GUI which is not compatible with our screen resolution. Moreover the Mks UI is incomplete for the management of Deltas functions.

Now that version 2.1.1 is released, I will have some time to redo firmwares for the Wifi module with the last ESP3D source.

**Comment by Foxies-CSTL** [comment]
The firmwares for the WIFI module will be updated. I have just finished different tests between remote hosts for monitoring and file transfer.
I used a TFT35v1 for the MKS(lvgl) UI and the COLOR UI from Marlin. I will make a table to show the capabilities.

**Comment by Foxies-CSTL** [comment]
Update firmware ESP3Dv2.1/v3 for UI COLOR (Stock) and UI MKS (ex:TFT35v1)
- TFT_COLOR_UI (monitoring) 
- TFT_LVGL_UI(Monitoring+TransfertData)
Note: Need a firmware with option "w" and "I" instead "W".

Close this issue
