### ISSUE TITLE
FILAMENT SENSOR AND POWERLOSS RECOVERY NO WORK

### ISSUE THREAD

**Issue by matiasdj87** [Foxies-CSTL/Marlin_2.1.x#21]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

FILAMENT SENSOR NOT WORK and POWERLOSS RECOVERY NOT WORK.... with SCWTPULR-Robin_mini.bin STOCK FIRMWARE... but with QQS Repetier Firmware its works fine. M412 is ON and M119 is tiggered or open if the filament is charged or no..

### Version of Marlin Firmware

2.1.2

### Printer model

FLSUN QQS PRO

### Electronics

MKS ROBIN MINI

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Simplify3D

### Host Software

SD Card (headless)

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by Foxies-CSTL** [comment]
Hi,
These two options are available via the "Configuation" menu ("Runout" and "power_Outage") and you need to activate them (toogle button) and then save their position by saving settings (configuation menu).
Note: Power_Outage" works only with SD_card print. No with Host print.

**Comment by cpeg78** [comment]
Hello, when I turn on runout, the printer is stopping and wants to change filament. Filament was correctly loaded and sensor light is blue.

**Comment by Foxies-CSTL** [comment]
> when I turn on runout, the printer is stopping and wants to change filament. Filament was correctly loaded and sensor light is blue.

Hi,
You can check the correct operation of the filament sensor with the M119 command, which will give you an indication of the ON/OFF status in the terminal.

![image](https://github.com/Foxies-CSTL/Marlin_2.1.x/assets/24864147/f1036faf-b4e7-4f9f-be2d-d0787e87b38a)

If you don't have the "TRIGGERED" state when the filament is inserted, then you've got reverse detection.

**Comment by cpeg78** [comment]
Hi,thanks for your answer. Is it possible to change the detection? On my Ender 3 V2, I can change it from High to Low, but can‘t find such setting on my Q5.Am 30.08.2023 um 16:36 schrieb Foxies ***@***.***>:﻿

when I turn on runout, the printer is stopping and wants to change filament. Filament was correctly loaded and sensor light is blue.

Hi,
You can check the correct operation of the filament sensor with the M119 command, which will give you an instantiation of the ON/OFF status in the terminal.

If you don't have the "TRIGGERED" state when the filament is inserted, then you've got reverse detection.

**Comment by Foxies-CSTL** [comment]
> Is it possible to change the detection?

Yes, this is possible in the firmware, but it may be easier to invert the wires if you have a 2-wire detector: 1 wire for signal and 1 wire for ground.

**Comment by Foxies-CSTL** [comment]
> I can change it from High to Low, but can‘t find such setting on my Q5

Yes here in the "Configuration.h" file

![image](https://github.com/Foxies-CSTL/Marlin_2.1.x/assets/24864147/3657444f-6779-4685-bef0-3459e3d7849d)

**Comment by cpeg78** [comment]
I already had this idea. Its a cheap on from ebay, with 3 wires.

**Comment by Foxies-CSTL** [comment]
> I already had this idea. Its a cheap on from ebay, with 3 wires.

I answered earlier for configuration.h file ;-)
