### ISSUE TITLE
[BUG] M118 Output to SERIAL_PORT_2

### ISSUE THREAD

**Issue by mulcmu** [Foxies-CSTL/Marlin_2.1.x#6]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

`M118` only outputs blank lines to secondary serial port.  Other text to secondary serial port is received okay such as temperature auto reports.

`M118 P0 TEST` and `M118 P2 TEST` only output blank lines to `SERIAL_PORT_2`

### Bug Timeline

Old issue

### Expected behavior

String provided to `M118` should be output to ports specified by `P` parameter.

### Actual behavior

`M118` output to secondary serial port is only a blank line for each 

### Steps to Reproduce

Send `M118P0TEST` or `M118P2TEST` in host software results in blank line output on secondary serial port.

Same behavior when above included in gcode printed from SD card.

### Version of Marlin Firmware

Foxies-CSTL/Marlin_2.1.x fork for FLSUN printers

### Printer model

FLSUN QQ-S Pro

### Electronics

Stock

### Add-ons

`SERIAL_PORT_2` is connected to an ESP8266 module installed in the motherboard.  ESP8266 is running ESPHOME

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Cura

### Host Software

Pronterface

### Don't forget to include

- [X] #7

### Additional information & file uploads

See https://github.com/Foxies-CSTL/Marlin_2.1.x for QQSP configuration.

I wasn't able to find root cause but tested a work around:

https://github.com/MarlinFirmware/Marlin/blob/e201f4e656f787666420cc157d5efd436c1bbb14/Marlin/src/gcode/host/M118.cpp#L59

was replaced with 
```
  SERIAL_ECHO(p);
  SERIAL_EOL();
```
and expected behavior was confirmed.  String was output on secondary serial port by `M118`

`SERIAL_ECHOLN(p)` seems to treat `p` as string pointer by the primary serial port but only as a char on the secondary serial port.  Bug might be more general that `SERIAL_ECHOLN(char *)` behaves differently based on port or underlying serial stream/device.

**Comment by mulcmu** [comment]
See https://github.com/MarlinFirmware/Marlin/issues/24671 for additional discussion.

**Comment by Foxies-CSTL** [comment]
I configured my printer with 4x2209Standalone + Wifi module with ESP2.1 + firmware BugFix2.1.1 => RAS.
I will do some tests and start working with the Wifi module and I will download your ESP firmware to do some tests.
See you later ;-)

**Comment by mulcmu** [comment]
I create a new [branch ](https://github.com/mulcmu/Marlin_2.1.x/tree/mulcmu_v5)on my fork from your latest FLSUN-STABLE branch and made the configuration changes for my machine.  The bug behavior was confirmed when M118.cpp uses SERIAL_ECHOLN();

My ESPHome module would be a lot of work to setup unless you already have home assistant available to build it and test.  I can flash ESP3D 2.1 to my wifi module to help narrow down the root cause.

**Comment by Foxies-CSTL** [comment]
> I create a new [branch ](https://github.com/mulcmu/Marlin_2.1.x/tree/mulcmu_v5)on my fork

Ok, I worked a little on the firmwares of the WIFI module. I tested the MKSwifi, Mischianti, ESP3Dv2 and V3 to define the properties of each in moniroting and file transfer. This allowed me to adjust the MoBo pins file according to the UI used (Marlin COLOR and MKS lgvl).
Finally I made tests between console/terminal and the tests are conclusive:
OCTO(M118 P2 Test P2 From OCTO) to ESP3D and I get well the "Test P2 From OCTO" in echo and vice versa. So it came from my pin definition and not from the M118.cpp file.

OCTO
![image](https://user-images.githubusercontent.com/24864147/188525010-3612cb77-f079-4cb4-a23d-be372d19fa31.png)

ESP3Dv3
![image](https://user-images.githubusercontent.com/24864147/188524887-0e316edd-166a-4b07-8b2f-8d0423b10d66.png)

ESPD3v3
![image](https://user-images.githubusercontent.com/24864147/188525041-33dc8fa6-85a6-4d3b-9c78-8fd5b44a0f6a.png)

You can find all the modifications on my development branch "FLSUN_BUGFIX-MULTI". https://github.com/Foxies-CSTL/Marlin_2.1.x/commit/65190f7b570e4a58aef577d4ed8d366abea2d3e3
