### ISSUE TITLE
Publish config files

### ISSUE THREAD

**Issue by hashat** [Foxies-CSTL/Marlin_2.1.x#9]
### Describe the feature you want

While the pre-compiled [firmwares](https://github.com/Foxies-CSTL/Marlin_2.1.x/tree/Firmwares/QQSP) work great overall (thanks!!), I'd like to make small adjustments to config to experiment further. Is there any way you could publish the firmware configs used to compile U9CGTmPULR32, U9CGgTmPULR32, ... ? I found that [CONFIGURATION_EMBEDDING](https://github.com/Foxies-CSTL/Marlin_2.1.x/blob/bugfix-2.1.x/docs/ConfigEmbedding.md) might also be an option, but I could not find the mc.zip (probably space constraints?).
So the question is: can you publish your premade firmware configs, or is it already existing somewhere on GitHub I just can't find it?

Thanks.

**Comment by Foxies-CSTL** [comment]
Hi,
Indeed it is a space constraint with the option activated. But if you use the options present in the header (in the file FLSUNQ_Config.h) by using my sources you will notice that the option "CONFIGURATION_EMBEDDING" prevents the generation of the mc.zip.
This one is in the same place as the generated binary.
